# Global Variables

title: Phoenix Post Productions
description: >
  Indie films and freelance editing
keywords: # a YAML list. optional; only used by some older search engines.
baseurl: # for hosting at a subdomain
url: https://phoenixpostproductions.netlify.com # full url of main site
logo:
  header: /assets/logo/logo-simple.png
  full: /assets/logo/logo-decorative-black.png
og_image: # default og image used for entire site; can be overridden if specified in page or collection frontmatter
google_analytics: # tracking number
permalink: /:title/ # default permalink structure for pages
copyright:
  date: 2019-05-31T17:24:00-4:00 # date the site was created
  owner: Site Owner # owner of the site

timezone: America/New_York # used for liquid-generated datetimes
auto_scroll: false # enables smooth scrolling for all same-page links using zenscroll
native_scroll: false # enables smooth scrolling by the scroll-behavior property, for all browsers that support it
bg_testing: false # turn on to enable the bg-testing.html include
emptyArray: [] # variable for easy array creation

# Build settings

markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile*"
  - "package*.json"
  - "node_modules"
  - "gulpfile.js"
  - "assets/test"
