---
---

# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway
  branch: master
media_folder: "assets/uploads"
site_url: {{ site.url }}
{% if site.logo.full %}
logo_url: {{ site.logo.full }}
{% endif %}
collections:
  - label: Videos
    name: videos
    files:
      - label: Videos Page
        name: videos-page
        file: _data/videos.yml
        fields:
          - label: Categories
            name: categories
            widget: list
            fields:
              - label: Name
                name: name
                widget: string
              - label: Videos
                name: videos
                widget: list
                fields:
                  - label: Title
                    name: title
                    widget: string
                  - label: Date
                    name: date
                    widget: date
                    format: YYYY-MM-DD hh:mm:ss
                  - label: Media
                    name: media
                    widget: select
                    options:
                      - Vimeo
                      - YouTube
                    default: Vimeo
                  - label: URL
                    name: link
                    widget: string
                  - label: Published
                    name: published
                    widget: boolean
  - label: Data
    name: data
    description: >
      This is where you will be able to update different
      types of data, which are used throughout the site.
    files:
      - label: Site Data
        name: site
        file: _config.yml
        fields:
          - label: Site title
            name: title
            widget: string
          - label: Site description
            name: description
            widget: string
          - label: Copyright
            name: copyright
            widget: object
            fields:
              - label: Copyright date
                name: date
                widget: datetime
                format: "YYYY-MM-DDTHH:MM:SSZ"
                hint: >
                  Usually the date the site was created,
                  unless otherwise renewed.
              - label: Site owner
                name: owner
                widget: string
          - label: Site image
            name: og_image
            required: false
            widget: image
            allow_multiple: false
          - label: Google Analytics
            name: google_analytics
            required: false
            widget: string
            hint: >
              Enter your tracking number to turn on analytics
              for the site.
      - label: Contact info
        name: contact
        file: _data/contact.yml
        fields: {% for c in site.data.contact %}
          - label: {{ c[0] | capitalize }}
            name: {{ c[0] }}
            required: false
            widget: string {% endfor %}
